# Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [41]:
list = [2,4,6,8,10]

In [42]:
# add one element at the end
list.append(12)
list

[2, 4, 6, 8, 10, 12]

In [43]:
# add multiple element at the end 
list.extend([14,16])
list

[2, 4, 6, 8, 10, 12, 14, 16]

In [44]:
# adds an element at a specific position
list.insert(2, 5)
list

[2, 4, 5, 6, 8, 10, 12, 14, 16]

In [45]:
# Removes a specific element
list.remove(5)
list

[2, 4, 6, 8, 10, 12, 14, 16]

In [46]:
# remove the last element
list.pop()
list

[2, 4, 6, 8, 10, 12, 14]

In [47]:
# Finds the position of a element
list.index(8)

3

In [49]:
# Counts how many times a element appears
list.count(12)

1

In [51]:
# Arranges list in ascending order
list2 = [4,7,9,5,6,2,1]
list2.sort()
list2

[1, 2, 4, 5, 6, 7, 9]

In [54]:
# Reverses the list
list.reverse()
list

[14, 12, 10, 8, 6, 4, 2]

In [55]:
# Removes all elements from the list
list2.clear()
list2

[]

### 2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why

In [1]:
# Create a tuple with 3 student names
students = ("Arif bhai", "izmamul bhai", "janesar bhai")

print("Original Tuple:", students)

# Try to change second name
students[1] = "Amir bhai"

Original Tuple: ('Arif bhai', 'izmamul bhai', 'janesar bhai')


TypeError: 'tuple' object does not support item assignment

### A tuple is immutable
### This means you cannot change its values after creation

### 3.	Create a set of integers with some duplicate values. Print the set and explain the output

In [58]:
# Create a set with duplicate values
numbers = {1, 2, 3, 4, 2, 3, 5}

print("Set:", numbers)

Set: {1, 2, 3, 4, 5}


### A set does not allow duplicate values, When you create a set with duplicates, Python automatically removes duplicates

### 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [3]:
student_001 = {"name" : "AM BAKSH",
                   "age" : 25,
                   "city" : "patna"}
# update age
student_001["age"] = 30

# add new key
student_001["email"] = "ambaksh23@gmail.com"

# print final dictionary
print(student_001)

{'name': 'AM BAKSH', 'age': 30, 'city': 'patna', 'email': 'ambaksh23@gmail.com'}


### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message

In [4]:
# Age variable
age = 20

# Check voting eligibility
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'


In [6]:
# Marks variable
marks = 82

# Check grade
if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")

Grade: B


 ### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [7]:
# Given number
num = 10

# Check conditions
if num > 0:
    if num % 2 == 0:
        print("Positive and Even number")
    else:
        print("Positive but Odd number")
elif num == 0:
    print("Number is Zero")
else:
    print("Negative number")

Positive and Even number


## Section B: Numpy

### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [8]:
import numpy as np

# Scalar
scalar = np.array(5)
print("Scalar:", scalar)

# 1D array (1 to 5)
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

# 2D array (2x3) with values 10 to 60
arr2d = np.array([[10, 20, 30],
                  [40, 50, 60]])
print("2D Array:\n", arr2d)

Scalar: 5
1D Array: [1 2 3 4 5]
2D Array:
 [[10 20 30]
 [40 50 60]]


### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [10]:
import numpy as np

# Generate 4x4 array with random integers (0 to 100)
arr = np.random.randint(0, 101, (4, 4))

print("4x4 Random Array:\n", arr)

4x4 Random Array:
 [[ 22  32  54  52]
 [ 14 100  65  92]
 [ 59  24  89  36]
 [ 61  31  45  28]]


### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [12]:
import numpy as np
import pandas as pd

# Create 3x3 NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Convert to DataFrame and add column names
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


## Section C: Exploring Pandas

### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [14]:
import pandas as pd
import numpy as np

In [26]:
# Create DataFrame with 10 rows
data = {
    "Name": ["baksh", "amir", "janisar", "izmamul", "arif", "atif", "maruf", "sharuk", "qasim", "adil"],
    "Age": [22, 25, 23, 24, 26, 28, 21, 27, 29, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Delhi", "Chennai", "Kolkata", "Delhi", "Mumbai", "Pune", "Delhi"],
    "Salary": [30000, 40000, np.nan, 35000, 45000, np.nan, 32000, 41000, 38000, 30000]
}

In [27]:
df = pd.DataFrame(data)

print("Original DataFrame:\n", df)


Original DataFrame:
       Name  Age     City   Salary
0    baksh   22    Delhi  30000.0
1     amir   25   Mumbai  40000.0
2  janisar   23     Pune      NaN
3  izmamul   24    Delhi  35000.0
4     arif   26  Chennai  45000.0
5     atif   28  Kolkata      NaN
6    maruf   21    Delhi  32000.0
7   sharuk   27   Mumbai  41000.0
8    qasim   29     Pune  38000.0
9     adil   22    Delhi  30000.0


In [28]:
# 1. info() and describe()
print("\nInfo:")
print(df.info())



Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes
None


In [29]:
print("\nDescribe:")
print(df.describe())


Describe:
             Age       Salary
count  10.000000      8.00000
mean   24.700000  36375.00000
std     2.750757   5527.52851
min    21.000000  30000.00000
25%    22.250000  31500.00000
50%    24.500000  36500.00000
75%    26.750000  40250.00000
max    29.000000  45000.00000


In [30]:
# 2. Select 'Name' and 'City'
print("\nSelected Columns:")
print(df[["Name", "City"]])


Selected Columns:
      Name     City
0    baksh    Delhi
1     amir   Mumbai
2  janisar     Pune
3  izmamul    Delhi
4     arif  Chennai
5     atif  Kolkata
6    maruf    Delhi
7   sharuk   Mumbai
8    qasim     Pune
9     adil    Delhi


In [31]:
# 3. Drop 'City' column
df = df.drop("City", axis=1)
print("\nAfter Dropping City:\n", df)



After Dropping City:
       Name  Age   Salary
0    baksh   22  30000.0
1     amir   25  40000.0
2  janisar   23      NaN
3  izmamul   24  35000.0
4     arif   26  45000.0
5     atif   28      NaN
6    maruf   21  32000.0
7   sharuk   27  41000.0
8    qasim   29  38000.0
9     adil   22  30000.0


In [32]:
# 4. Fill missing values in Salary with mean
df["Salary"].fillna(df["Salary"].mean(), inplace=True)
print("\nAfter Filling Missing Salary:\n", df)


After Filling Missing Salary:
       Name  Age   Salary
0    baksh   22  30000.0
1     amir   25  40000.0
2  janisar   23  36375.0
3  izmamul   24  35000.0
4     arif   26  45000.0
5     atif   28  36375.0
6    maruf   21  32000.0
7   sharuk   27  41000.0
8    qasim   29  38000.0
9     adil   22  30000.0


C:\Users\SHAIKH\AppData\Local\Temp\ipykernel_8596\2739549230.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace=True)


In [33]:
# 5. Remove duplicate rows
df = df.drop_duplicates()
print("\nAfter Removing Duplicates:\n", df)


After Removing Duplicates:
       Name  Age   Salary
0    baksh   22  30000.0
1     amir   25  40000.0
2  janisar   23  36375.0
3  izmamul   24  35000.0
4     arif   26  45000.0
5     atif   28  36375.0
6    maruf   21  32000.0
7   sharuk   27  41000.0
8    qasim   29  38000.0
9     adil   22  30000.0
